name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo dpkg --configure -a
          sudo rm -f /var/lib/dpkg/lock-frontend
          sudo apt-get update -y 
          sudo apt install python3-pip
          
          sudo pip3 install mercury
          sudo ./scripts/pack_mercury.sh
          sudo pip3 install --upgrade setuptools
          
          cd mercury
          sudo pip3 install -g -r requirements.txt
      - name: Test backend
        run: |
          cd mercury
          sudo python manage.py test apps
